title:            Blog by Ben Clark-Robinson
description:      Technology
paginate:         5
url:              http://benclarkrobinson.net
signoff:          Ben
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   929185340466821 # appid for like button, remove from /_includes/share.html if unwanted.
twitter_via:      bclarkrobinson # twitter handle for tweet 'via'
google_analytics: UA-1948867-4
excerpt_separator: <!--more-->
theme: jekyll-theme-cayman

links:
  - name:         Twitter
    url:          https://twitter.com/bclarkrobinson
    external:     true
  - name:         LinkedIn
    url:          https://au.linkedin.com/in/benclarkrobinson
    external:     true
  - name:         GitHub
    url:          http://github.com/mozketo
    external:     true
  - name:         Download FreqPress
    url:          /apps/2014/07/18/announcing-freq-press-alpha-key-counter-for-windows/
nav:
  - name:         RSS
    url:          /feed.xml 
    rel:          alternate
    type:         application/atom+xml
permalink:        pretty
markdown:         kramdown